import Game.Levels.ThirdCyclotomicExtensions.L01_Units_mem
import Game.Levels.ThirdCyclotomicExtensions.L02_Units_not_exists_int_three_dvd_sub
import Game.Levels.ThirdCyclotomicExtensions.L03_lambda_sq
import Game.Levels.ThirdCyclotomicExtensions.L04_eq_one_or_neg_one_of_unit_of_congruent
import Game.Levels.ThirdCyclotomicExtensions.L05_norm_lambda
import Game.Levels.ThirdCyclotomicExtensions.L06_norm_lambda_prime
import Game.Levels.ThirdCyclotomicExtensions.L07_lambda_dvd_three
import Game.Levels.ThirdCyclotomicExtensions.L08_lambda_prime
import Game.Levels.ThirdCyclotomicExtensions.L09_lambda_ne_zero
import Game.Levels.ThirdCyclotomicExtensions.L10_lambda_not_unit
import Game.Levels.ThirdCyclotomicExtensions.L11_card_quot
import Game.Levels.ThirdCyclotomicExtensions.L12_two_ne_zero
import Game.Levels.ThirdCyclotomicExtensions.L13_lambda_not_dvd_two
import Game.Levels.ThirdCyclotomicExtensions.L14_univ_quot
import Game.Levels.ThirdCyclotomicExtensions.L15_dvd_or_dvd_sub_one_or_dvd_add_one
import Game.Levels.ThirdCyclotomicExtensions.L16_toInteger_cube_eq_one
import Game.Levels.ThirdCyclotomicExtensions.L17_eta_isUnit
import Game.Levels.ThirdCyclotomicExtensions.L18_toInteger_eval_cyclo
import Game.Levels.ThirdCyclotomicExtensions.L19_cube_sub_one
import Game.Levels.ThirdCyclotomicExtensions.L20_lambda_dvd_mul_sub_one_mul_sub_eta_add_one
import Game.Levels.ThirdCyclotomicExtensions.L21_lambda_pow_four_dvd_cube_sub_one_of_dvd_sub_one
import Game.Levels.ThirdCyclotomicExtensions.L22_lambda_pow_four_dvd_cube_add_one_of_dvd_add_one
import Game.Levels.ThirdCyclotomicExtensions.L23_lambda_pow_four_dvd_cube_sub_one_or_add_one_of_lambda_not_dvd

World "ThirdCyclotomicExtensions"
Title "Third Cyclotomic Extensions"

Introduction "
Welcome to the world *Third Cyclotomic Extensions*.
"
