import Game.Metadata
import Game.Levels.ThirdCyclotomicExtensions.L13_lambda_not_dvd_two

World "ThirdCyclotomicExtensions"
Level 14

Title "univ_quot"

Introduction "
Let $K = \\Q(\\zeta_3)$ be the third cyclotomic field. \\\\
Let $\\cc{O}_K = \\Z[\\zeta_3]$ be the ring of integers of $K$. \\\\
Let $\\cc{O}^\\times_K$ be the group of units of $\\cc{O}_K$. \\\\
Let $\\zeta_3 \\in K$ be any primitive third root of unity. \\\\
Let $\\eta \\in \\cc{O}_K$ be the element corresponding to $\\zeta_3 \\in K$. \\\\
Let $\\lambda \\in \\cc{O}_K$ be such that $\\lambda = \\eta -1$. \\\\
Let $I$ be the ideal generated by $\\lambda$. \\\\\\\\
Then $\\cc{O}_K / I = \\set{0, 1, -1}$.
"

namespace NumberField
end NumberField

namespace NumberField.Units
end NumberField.Units

section
open NumberField
open Units
open InfinitePlace
open nonZeroDivisors
open Polynomial

namespace IsCyclotomicExtension.Rat.Three

attribute [local instance] _root_.IsPrimitiveRoot.IsCyclotomicExtension.ringOfIntegers
attribute [local instance] _root_.IsCyclotomicExtension.ring_of_integers'
attribute [local instance] _root_.NumberField.Units._instance_m464c54332e4d6174686c69622e4e756d6265725468656f72792e4e756d6265724669656c642e556e697473_l115
attribute [local instance] _root_.NumberField.Units._instance_m464c54332e4d6174686c69622e4e756d6265725468656f72792e4e756d6265724669656c642e556e697473_l118
attribute [local instance] _root_.NumberField.Units._instance_m464c54332e4d6174686c69622e4e756d6265725468656f72792e4e756d6265724669656c642e556e697473_l129
attribute [local instance] _root_.NumberField.Units._instance_m464c54332e4d6174686c69622e4e756d6265725468656f72792e4e756d6265724669656c642e556e697473_l132
attribute [local instance] _root_.NumberField.Units.instDiscrete_unitLattice
attribute [local instance] _root_.NumberField.Units.instZlattice_unitLattice
attribute [local instance] _root_.NumberField.Units._instance_m464c54332e4d6174686c69622e4e756d6265725468656f72792e4e756d6265724669656c642e556e697473_l510
attribute [local instance] _root_.NumberField.Units._instance_m464c54332e4d6174686c69622e4e756d6265725468656f72792e4e756d6265724669656c642e556e697473_l513
attribute [local instance] _root_.NumberField.Units._instance_m464c54332e4d6174686c69622e4e756d6265725468656f72792e4e756d6265724669656c642e556e697473_l519
attribute [local instance] _root_.NumberField.Units._instance_m464c54332e4d6174686c69622e4e756d6265725468656f72792e4e756d6265724669656c642e556e697473_l532
variable {K : Type*} [Field K] [NumberField K] [IsCyclotomicExtension {3} ℚ K]
variable {ζ : K} (hζ : IsPrimitiveRoot ζ ↑(3 : ℕ+)) (u : (𝓞 K)ˣ)
local notation "η" => hζ.toInteger
local notation "λ" => hζ.toInteger - 1
attribute [local instance] _root_.IsCyclotomicExtension.Rat.Three._instance_m464c54332e4379636c6f_l177
attribute [local instance] _root_.IsCyclotomicExtension.Rat.Three._instance_m464c54332e4379636c6f_l283
attribute [local instance] _root_.IsCyclotomicExtension.Rat.Three._instance_m464c54332e4379636c6f_l286
attribute [local instance 10000] _root_.Ring.toNeg
attribute [local instance 10000] _root_.Ring.toAddCommGroup
attribute [local instance 10000] _root_.NeZero.one
open Classical
open Finset

/-- Let $K = \Q(\zeta_3)$ be the third cyclotomic field. \\
Let $\cc{O}_K = \Z[\zeta_3]$ be the ring of integers of $K$. \\
Let $\cc{O}^\times_K$ be the group of units of $\cc{O}_K$. \\
Let $\zeta_3 \in K$ be any primitive third root of unity. \\
Let $\eta \in \cc{O}_K$ be the element corresponding to $\zeta_3 \in K$. \\
Let $\lambda \in \cc{O}_K$ be such that $\lambda = \eta -1$. \\
Let $I$ be the ideal generated by $\lambda$. \\\\
Then $\cc{O}_K / I = \set{0, 1, -1}$. -/
TheoremDoc IsCyclotomicExtension.Rat.Three.univ_quot as "univ_quot" in "Third Cyclotomic Extensions"

Statement univ_quot : (univ : Finset ((𝓞 K ⧸ Ideal.span {λ}))) = {0, 1, -1} := by
  Hint "By *lmm:card_quot*, the cardinality of $\\cc\u007bO\u007d_K / I$ is $3$,
so it suffices to prove that $1,-1$ and $0$ are distinct.\\\\
We proceed by contradiction analysing each case:
\\begin\u007bitemize\u007d
\\item Case $1 = -1$. By basic algebraic properties, $1 = -1$ implies that $2 = 0$,
which contradicts *lmm:two_ne_zero* forcing us to conclude that $1 \\neq -1$.
\\item Case $1 = 0$. Trivial contradiction.
\\item Case $-1 = 0$. It implies that $1 = 0$, which is a contradiction.
\\end\u007bitemize\u007d"
  refine (eq_of_subset_of_card_le (fun _ _ ↦ mem_univ _) ?_).symm
  rw [card_univ, _root_.IsCyclotomicExtension.Rat.Three.card_quot hζ, card_insert_of_not_mem, card_insert_of_not_mem, card_singleton]
  · rw [mem_singleton]
    intro h
    rw [← add_eq_zero_iff_eq_neg, one_add_one_eq_two] at h
    exact _root_.IsCyclotomicExtension.Rat.Three.two_ne_zero hζ h
  · intro h
    simp only [mem_insert, mem_singleton, zero_eq_neg] at h
    rcases h with (h | h)
    · exact zero_ne_one h
    · exact zero_ne_one h.symm

NewDefinition IsCyclotomicExtension.Rat.Three._instance_m464c54332e4379636c6f_l283 IsCyclotomicExtension.Rat.Three._instance_m464c54332e4379636c6f_l286
NewTheorem Finset.eq_of_subset_of_card_le Finset.mem_univ zero_ne_one
run_cmd _root_.ProofQuest.completeInventory _root_.ProofQuest.exerciseNames

end IsCyclotomicExtension.Rat.Three

end

Conclusion "Level completed! 🎉"
